name: Master build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name : Cache Dotnent Packages
      id: cachedotnet
      uses: actions/cache@v2
      with:
        path: | 
         ~/.nuget/packages
         !~/.nuget/packages/unwanted
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restore dependencies
      if: steps.cachedotnet.outputs.cache-hit != 'true'
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Publish
      run: dotnet publish -c Release -o publish --no-restore

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
          name: master-artifact
          path: /home/runner/work/CI-CD-NetCoreProj/CI-CD-NetCoreProj/publish/

    - name: Test
      run: dotnet test --no-build --verbosity normal
