name: Dev build

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore

    - name: Publish
      run: dotnet publish --no-restore

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
          name: dev-artifact
          path: /home/runner/work/CI-CD/CI-CD/CICDDemoNetCoreProj/bin/Debug/netcoreapp3.1/publish/

    - name: Test
      run: dotnet test --no-build --verbosity normal
